// <auto-generated />
using System;
using ExcelsiorLuxury.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelsiorLuxury.Data.Migrations
{
    [DbContext(typeof(ExcelsiorLuxuryDbContext))]
    [Migration("20260324151947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZCategorias");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZDireccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("ZDirecciones");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo_Envio")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<string>("Estado_Envio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_Entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Salida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Direccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Direccion");

                    b.ToTable("ZEnvios");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZMarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZMarcas");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZModelos");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Envio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor_Neto")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Envio");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("ZOrdenes");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZOrdenDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Orden")
                        .HasColumnType("int");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Orden");

                    b.HasIndex("Id_Producto");

                    b.ToTable("ZOrdenDetalles");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("Id_Categoria")
                        .HasColumnType("int");

                    b.Property<int>("Id_Marca")
                        .HasColumnType("int");

                    b.Property<int>("Id_Modelo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Categoria");

                    b.HasIndex("Id_Marca");

                    b.HasIndex("Id_Modelo");

                    b.ToTable("ZProductos");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZUsuarios");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZDireccion", b =>
                {
                    b.HasOne("ExcelsiorLuxury.Data.Entities.ZUsuario", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZEnvio", b =>
                {
                    b.HasOne("ExcelsiorLuxury.Data.Entities.ZDireccion", "Direccion")
                        .WithMany("Envios")
                        .HasForeignKey("Id_Direccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZOrden", b =>
                {
                    b.HasOne("ExcelsiorLuxury.Data.Entities.ZEnvio", "Envio")
                        .WithMany("Ordenes")
                        .HasForeignKey("Id_Envio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExcelsiorLuxury.Data.Entities.ZUsuario", "Usuario")
                        .WithMany("Ordenes")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Envio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZOrdenDetalle", b =>
                {
                    b.HasOne("ExcelsiorLuxury.Data.Entities.ZOrden", "Orden")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("Id_Orden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExcelsiorLuxury.Data.Entities.ZProducto", "Producto")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZProducto", b =>
                {
                    b.HasOne("ExcelsiorLuxury.Data.Entities.ZCategoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Id_Categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExcelsiorLuxury.Data.Entities.ZMarca", "Marcas")
                        .WithMany("Productos")
                        .HasForeignKey("Id_Marca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExcelsiorLuxury.Data.Entities.ZModelo", "Modelos")
                        .WithMany("Productos")
                        .HasForeignKey("Id_Modelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marcas");

                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZCategoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZDireccion", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZEnvio", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZMarca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZModelo", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZOrden", b =>
                {
                    b.Navigation("OrdenDetalles");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZProducto", b =>
                {
                    b.Navigation("OrdenDetalles");
                });

            modelBuilder.Entity("ExcelsiorLuxury.Data.Entities.ZUsuario", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
